[package]
name = "single-notch"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Iced-based GUI for SingleCLI"

[dependencies]
iced.workspace = true
single-core = { path = "../single-core" }
single-protocol = { path = "../single-protocol" }
single-runtime = { path = "../single-runtime" }
single-tui = { path = "../single-tui" }