[package]
name = "divisi-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
directories.workspace = true
chrono.workspace = true
rusqlite.workspace = true
tar.workspace = true
age.workspace = true
divisi-protocol = { path = "../divisi-protocol" }

[dev-dependencies]
tempfile = "3"
