//! Canonical divisi directory layout, per spec section 7.
//!
//! `~/.config/divisi/` holds config, profiles, agent registry overrides, and
//! runtime state. Only the subdirectories Phase 1 actually reads/writes are
//! created eagerly; the rest of the documented layout (mcp/, lsp/, skills/,
//! ...) is created on first use by later phases.

use anyhow::{Context, Result};
use std::path::PathBuf;

#[derive(Debug, Clone)]
pub struct DivisiDirs {
    root: PathBuf,
}

impl DivisiDirs {
    /// Resolves `~/.config/divisi` (or `$DIVISI_CONFIG_DIR` override, used by tests
    /// and by anyone who wants an isolated instance).
    pub fn discover() -> Result<Self> {
        if let Ok(dir) = std::env::var("DIVISI_CONFIG_DIR") {
            return Ok(Self { root: PathBuf::from(dir) });
        }
        let base = directories::BaseDirs::new()
            .context("could not determine home/config directory for this platform")?;
        Ok(Self { root: crate::migrate::resolve_default_root(base.config_dir()) })
    }

    pub fn from_root(root: PathBuf) -> Self {
        Self { root }
    }

    pub fn root(&self) -> &PathBuf {
        &self.root
    }

    pub fn config_file(&self) -> PathBuf {
        self.root.join("config.toml")
    }

    pub fn profiles_dir(&self) -> PathBuf {
        self.root.join("profiles")
    }

    pub fn agents_dir(&self) -> PathBuf {
        self.root.join("agents")
    }

    pub fn state_dir(&self) -> PathBuf {
        self.root.join("state")
    }

    pub fn socket_path(&self) -> PathBuf {
        self.state_dir().join("runtime.sock")
    }

    pub fn db_path(&self) -> PathBuf {
        self.state_dir().join("divisi.db")
    }

    pub fn logs_dir(&self) -> PathBuf {
        self.root.join("logs")
    }

    pub fn mcp_registry_file(&self) -> PathBuf {
        self.root.join("mcp.toml")
    }

    /// Per-(agent, optional account) opt-in Docker execution settings —
    /// see `divisi_core::docker`.
    pub fn docker_registry_file(&self) -> PathBuf {
        self.root.join("docker.toml")
    }

    /// Per-agent opt-in mid-run permission interception settings — see
    /// `divisi_core::hooks`.
    pub fn hooks_registry_file(&self) -> PathBuf {
        self.root.join("hooks.toml")
    }

    /// Task-lifecycle event hooks (fire-a-command-on-completion) — see
    /// `divisi_core::task_hooks`. Deliberately a different file from
    /// `hooks_registry_file()` above; that's a different feature.
    pub fn task_hooks_registry_file(&self) -> PathBuf {
        self.root.join("task_hooks.toml")
    }

    /// Whether `divisi install-integrations` should sync only the
    /// `divisi-gateway` dynamic gateway into agents' native MCP config,
    /// instead of every enabled server in `mcp_registry_file()` — see
    /// `divisi_core::mcp::gateway_mode`.
    pub fn mcp_gateway_file(&self) -> PathBuf {
        self.root.join("mcp_gateway.toml")
    }

    pub fn lsp_registry_file(&self) -> PathBuf {
        self.root.join("lsp.toml")
    }

    pub fn tools_registry_file(&self) -> PathBuf {
        self.root.join("tools.toml")
    }

    pub fn permissions_file(&self) -> PathBuf {
        self.root.join("permissions.toml")
    }

    pub fn skills_dir(&self) -> PathBuf {
        self.root.join("skills")
    }

    /// Where account-switch profile snapshots live. Deliberately outside
    /// `state/` (which Phase 1 documented as cache/derived data) since
    /// these can contain live credentials and are user-authored, not
    /// regenerable.
    pub fn accounts_dir(&self) -> PathBuf {
        self.root.join("accounts")
    }

    pub fn providers_registry_file(&self) -> PathBuf {
        self.root.join("providers.toml")
    }

    /// Ordered agent/account fallback chains (`divisi_core::fallback`) —
    /// what to try next when a task run hits a detected rate limit.
    pub fn fallback_registry_file(&self) -> PathBuf {
        self.root.join("fallback.toml")
    }

    /// Labeled per-agent provider keys (`divisi_core::provider_keys`) — a
    /// separate registry from `providers.toml`'s single shared key per
    /// provider, so existing single-key setups are untouched by this file
    /// not existing yet.
    pub fn provider_keys_registry_file(&self) -> PathBuf {
        self.root.join("provider_keys.toml")
    }

    /// The billing-provider registry's admin/org-scoped key labels live
    /// in the same secret store as everything else (`billing:<provider>`
    /// namespace) — this file just tracks which providers have one set,
    /// so `divisi usage show` can report "no admin key configured" per
    /// provider instead of guessing from a failed API call.
    pub fn billing_registry_file(&self) -> PathBuf {
        self.root.join("billing.toml")
    }

    /// Generated by `divisi provider sync-pool` from
    /// `divisi_core::free_pool::FREE_PROVIDERS` — per-provider
    /// `enabled`/`disabled_reason` state (E28 spec §5.3/§17). Distinct
    /// from `providers.toml`, which carries the `single-<id>` preset
    /// metadata but has no `enabled` concept of its own.
    pub fn free_pool_registry_file(&self) -> PathBuf {
        self.root.join("free-pool.toml")
    }

    pub fn plugins_registry_file(&self) -> PathBuf {
        self.root.join("plugins.toml")
    }

    /// Coordinator agent routing table (`routing.toml`, spec E27.02 §5.4):
    /// per (kind, effort) capability-ranked agent lists. Seeded with
    /// defaults on first coordinator use.
    pub fn routing_file(&self) -> PathBuf {
        self.root.join("routing.toml")
    }

    /// Coordinator tunables (`coordinator.toml`, spec E27.02 §8):
    /// max_parallel, tick interval, per-goal dispatch/wall-clock caps,
    /// supervisor patch cap.
    pub fn coordinator_file(&self) -> PathBuf {
        self.root.join("coordinator.toml")
    }

    /// Root of every agent's divisi-managed `$HOME` (see
    /// `divisi-core::agent_home`). divisi runs agent CLIs, syncs their
    /// config, and captures/switches their credentials against
    /// `homes_dir()/<agent>/`, not the real, ambient `$HOME` — the real
    /// home is only ever read once, to bootstrap an agent's isolated home
    /// the first time it's used.
    pub fn homes_dir(&self) -> PathBuf {
        self.root.join("homes")
    }

    pub fn artifacts_dir(&self) -> PathBuf {
        self.state_dir().join("artifacts")
    }

    /// Where a finished task's full captured stdout+stderr lives.
    pub fn task_artifact_path(&self, id: i64) -> PathBuf {
        self.artifacts_dir().join(format!("task-{id}.txt"))
    }

    /// Where a task's output is tee'd *while it's still running* (see
    /// `divisi-agent-sdk::run::run_command_live`) — the TUI's task-detail
    /// view reads this file for a live view, then switches to
    /// `task_artifact_path` once the task finishes. Same naming
    /// convention on both ends (runtime writer, TUI reader) rather than a
    /// value passed over the socket, since both already agree on
    /// `DivisiDirs`.
    pub fn task_live_output_path(&self, id: i64) -> PathBuf {
        self.artifacts_dir().join(format!("task-{id}.live.txt"))
    }

    /// Where ingested documents' original files live, one subdirectory per
    /// document id (see `divisi-runtime::documents`). The OCR'd/extracted
    /// text itself is stored as an ordinary memory entry, not here — this
    /// only holds the source file plus enough to track provenance.
    pub fn documents_dir(&self) -> PathBuf {
        self.state_dir().join("documents")
    }

    /// Poll-interval settings for the notch UI's background poller — see
    /// `divisi_core::notch`.
    pub fn notch_file(&self) -> PathBuf {
        self.root.join("notch.toml")
    }

    /// Where the notch UI's background process records its PID, so a
    /// second launch can detect one is already running instead of
    /// spawning a duplicate poller.
    pub fn notch_pid_file(&self) -> PathBuf {
        self.state_dir().join("notch.pid")
    }

    /// The notch UI's own IPC socket — distinct from `socket_path()`
    /// (the daemon's runtime socket), since the notch is a separate
    /// process the daemon doesn't own.
    pub fn notch_socket_path(&self) -> PathBuf {
        self.state_dir().join("notch.sock")
    }

    /// Creates the subset of the directory tree Phase 1 needs. Never touches
    /// anything outside `self.root`.
    pub fn ensure_created(&self) -> Result<()> {
        for dir in [self.profiles_dir(), self.agents_dir(), self.state_dir(), self.logs_dir()] {
            std::fs::create_dir_all(&dir)
                .with_context(|| format!("creating {}", dir.display()))?;
        }
        Ok(())
    }
}

/// Project-local override directory (`.single/` in a project root), per spec
/// section 28.
pub fn project_config_path(project_root: &std::path::Path) -> PathBuf {
    project_root.join(".single").join("config.yaml")
}

/// The real, ambient `$HOME` — used **only** as a one-time bootstrap
/// source for `agent_home::ensure_bootstrapped`, and by anything that
/// needs to spawn an agent's real interactive login (which has to run
/// against a real filesystem location the OS/browser flow can round-trip
/// to). Nothing else in divisi should read or write through this path
/// directly — see `agent_home`'s module doc for why.
pub fn real_home_dir() -> Result<PathBuf> {
    if let Ok(dir) = std::env::var("DIVISI_HOME_DIR") {
        return Ok(PathBuf::from(dir));
    }
    directories::BaseDirs::new()
        .map(|b| b.home_dir().to_path_buf())
        .context("could not determine home directory")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn notch_paths_are_scoped_under_root() {
        let dirs = DivisiDirs::from_root(PathBuf::from("/tmp/single-test-root"));
        assert_eq!(dirs.notch_file(), PathBuf::from("/tmp/single-test-root/notch.toml"));
        assert_eq!(dirs.notch_pid_file(), PathBuf::from("/tmp/single-test-root/state/notch.pid"));
        assert_eq!(dirs.notch_socket_path(), PathBuf::from("/tmp/single-test-root/state/notch.sock"));
    }
}
